"""empty message

Revision ID: cc587f8d1bed
Revises: 
Create Date: 2022-03-26 11:35:54.644539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc587f8d1bed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('career', sa.Text(), nullable=True),
    sa.Column('income', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('questions_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questions_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questions_id', sa.Integer(), nullable=True),
    sa.Column('options_id', sa.Integer(), nullable=True),
    sa.Column('customers_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customers_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['options_id'], ['options.id'], ),
    sa.ForeignKeyConstraint(['questions_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('options')
    op.drop_table('questions')
    op.drop_table('customers')
    # ### end Alembic commands ###
